---
- name: Get all Bare Metal Host (BMH) CRs from {{ bmh_namespace }} namespace
  kubernetes.core.k8s_info:
    api_version: metal3.io/v1alpha1
    kind: BareMetalHost
    namespace: "{{ bmh_namespace }}"
  register: bmh_crs_output
  environment:
    KUBECONFIG: "{{ proxy_kubeconfig | default(omit) }}"
    K8S_AUTH_PROXY: "{{ proxy_k8s_auth_proxy | default(omit) }}"
    HTTP_PROXY: "{{ proxy_http_proxy | default(omit) }}"
    HTTPS_PROXY: "{{ proxy_https_proxy | default(omit) }}"
    NO_PROXY: "{{ proxy_no_proxy | default(omit) }}"

- name: Set fact for BMH names, sorted alphabetically
  # Extract only the names from the BMH resources
  set_fact:
    bmh_names: "{{ bmh_crs_output.resources | map(attribute='metadata.name') | sort }}"
  when: bmh_crs_output.resources is defined and bmh_crs_output.resources | length > 0

- name: Process each Bare Metal Host found
  # Include process_bmh.yml tasks to process each BMH for better organization
  include_tasks: process_bmh.yml
  loop: "{{ bmh_names }}"
  loop_control:
    loop_var: current_bmh_name # This will be used by process_bmh.yml
  when: bmh_names is defined and bmh_names | length > 0
