- import_tasks: check_vars.yml
- name: ssh configuration
  copy:
    dest: .ssh/config
    content: |
      Host 192.168.111.*
      StrictHostKeyChecking=accept-new
      UserKnownHostsFile=~/.ssh/known_hosts_dev_vms
    mode: "644"

- name: Checkout openshift-metal3 dev-scripts
  git:
    dest: "{{dev_scripts_path}}"
    repo: "{{dev_scripts_src_repo}}"
    version: "{{ dev_scripts_branch }}"
- import_tasks: config.yml
